### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by aniketdikshit** [ricaun-io/RevitAddin.MultVersion#1]
Hey Ricaun, 
I found your Revit Template and your youtube video extremely helpful - thank you so much for that -
thought when I follow through with your steps as mentioned in the video and build my project or clone your project and build it - it gives me this error 
![image](https://github.com/ricaun-io/RevitAddin.MultVersion/assets/83564064/31f7c8f0-a684-4a90-a315-9c074f544f42)

I have a feeling it is related to the DLL not finding the correct version of the .net assembly - wondering if you had any thoughts about this or a fix?

**Comment by ricaun** [comment]
Hello!

Looks like your `.addin` file is pointing to the Application that does not exist in your assembly, maybe exist but is failing for some reason.
Are you sure the MultiVersionRevit.App class exists and is an IExternalApplication?

`I have a feeling it is related to the DLL not finding the correct version of the .net assembly - wondering if you had any thoughts about this or a fix?` If you are using the same .net framework as the template and trying to load in the right Revit version as you compile, should work fine.

**Comment by aniketdikshit** [comment]
Would you believe me if I told you a restart fixed all of it 😆

**Comment by ricaun** [comment]
It happens!
There is this discord channel about Autodesk Automation/Api: https://discord.gg/rkK23ENc
